# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.7
    hooks:
    -   id: ruff
        # Handle imports, see
        # https://github.com/astral-sh/ruff/issues/8232
        # https://github.com/astral-sh/ruff/issues/10882
        args: [ --fix, --extend-select, I ]
    -   id: ruff-format
        name: ruff format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    -   id: mypy
        name: mypy
        additional_dependencies: [types-requests]
