name: static-checks

on: [push]

jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 1

    - uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - uses: pre-commit/action@v3.0.1

    - name: Link Checker
      id: lychee
      uses: lycheeverse/lychee-action@v2
      with:
        fail: false
